#The name of this plugin, which is Spawny
name: Spawny
#Make up some crap for the description :P
description: An enhancement to the spawn system, allowing changing of spawns and teleporting to the spawn points
#Define the main class
main: com.massivedynamics.spawny.SpawnyPlugin
#Define the version
version: 1.2
#No database used! Yay!
database: false
#Of course I'm the author
author: CruzBishop, jascotty2
#K, command time
commands:
  #Lets you set the spawn
  setspawn:
    description: Sets the spawn point for the current world
    aliases: [sspawn, spawnset, changespawn, movespawn]
    permission: spawny.setspawn
    usage: "Syntax error! Usage is /setspawn"
  #Takes you to the spawn point
  spawn:
    description: Teleports to the spawn point for the current world
    aliases: [dospawn, executespawn]
    permission: spawny.spawn
    usage: "Syntax error! Usage is /spawn <worldName>"
#That was fun. Now for permissions!
permissions:
  spawny.*:
    description: Gives access to /spawn and /setspawn
    children:
      spawny.spawn: true
      spawny.setspawn: true
  spawny.spawn:
    description: Gives access to the /spawn command
    default: true
  spawny.setspawn:
    description: Gives access to the /setspawn command
    default: op