name: Spawny
description: An enhancement to the spawn system, allowing changing of spawns and teleporting to the spawn points
main: com.massivedynamics.spawny.SpawnyPlugin
version: 1.1.0.0 PREVIEW
database: false
author: CruzBishop
commands:
  setspawn:
    description: Sets the spawn point for the current world
    aliases: [sspawn, spawnset, changespawn, movespawn]
    permission: spawny.set
    usage: "Syntax error! Usage is /setspawn"
  spawn:
    description: Teleports to the spawn point for the current world
    aliases: [dospawn, executespawn]
    permission: spawny.spawn
    usage: "Syntax error! Usage is /spawn"
permissions:
  spawny.*:
    description: Gives access to /spawn and /setspawn
    children:
      spawny.spawn: true
      spawny.setspawn: true
  spawny.spawn:
    description: Gives access to the /spawn command
    default: true
  spawny.setspawn:
    description: Gives access to the /setspawn command
    default: op